using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using PCEFTPOS.EFTClient.IPInterface;
using PCEFTPOS.EFTClient.IPInterface.Slave;

namespace IPInterface.Test
{


    /// <summary>
    /// Generates a list of EFTRequests with default property values and strings generated by calling the
    /// EFTRequestToString function of DefaultMessageParser
    ///
    /// Useful as input to unit tests which aim to validate that they are sending correctly formatted messages
    /// </summary>

    internal class EftRequestsAndGeneratedStrings : IEnumerable<object[]>
    {

        private readonly List<object[]> _data = DefaultRequests.Select(r => new object[] { r, MessageParser.EFTRequestToString(r) }).ToList();


        private static readonly DefaultMessageParser MessageParser = new DefaultMessageParser();

        private static readonly IEnumerable<EFTRequest> DefaultRequests = new List<EFTRequest>()
        {
            new EFTChequeAuthRequest(),
            new EFTControlPanelRequest(),
            new EFTBasketDataRequest(),
            new EFTClientListRequest(),
            new EFTCloudLogonRequest(),
            new EFTCloudPairRequest(),
            new EFTCloudTokenLogonRequest(),
            new EFTConfigureMerchantRequest(),
            new EFTReprintReceiptRequest(),
            new EFTGetLastTransactionRequest(),
            new EFTHeartbeatRequest(),
            new EFTLogonRequest(),
            new EFTSendKeyRequest(),
            new EFTSettlementRequest(),
            new EFTTransactionRequest(),
            new EFTGetPasswordRequest(),
            new EFTQueryCardRequest(),
            new EFTReceiptRequest(),
            new SetDialogRequest(),
            new EFTStatusRequest(),
            new EFTSlaveRequest(),
            new EFTMonitoringRequest()
        };

        public IEnumerator<object[]> GetEnumerator()
        {
            return _data.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
    }
}
