//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPInterface.TestPOS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class ControlValues : global::System.Configuration.ApplicationSettingsBase {
        
        private static ControlValues defaultInstance = ((ControlValues)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ControlValues())));
        
        public static ControlValues Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CommonAppNumIdx {
            get {
                return ((int)(this["CommonAppNumIdx"]));
            }
            set {
                this["CommonAppNumIdx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00")]
        public string CommonMerchNum {
            get {
                return ((string)(this["CommonMerchNum"]));
            }
            set {
                this["CommonMerchNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CommonSelectedPad {
            get {
                return ((string)(this["CommonSelectedPad"]));
            }
            set {
                this["CommonSelectedPad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LogonTypeIdx {
            get {
                return ((int)(this["LogonTypeIdx"]));
            }
            set {
                this["LogonTypeIdx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TranIsOneButton {
            get {
                return ((bool)(this["TranIsOneButton"]));
            }
            set {
                this["TranIsOneButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TranIsETS {
            get {
                return ((bool)(this["TranIsETS"]));
            }
            set {
                this["TranIsETS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TranTxnRef {
            get {
                return ((string)(this["TranTxnRef"]));
            }
            set {
                this["TranTxnRef"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TranAutoTxnRef {
            get {
                return ((bool)(this["TranAutoTxnRef"]));
            }
            set {
                this["TranAutoTxnRef"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int TranTxnTypeIdx {
            get {
                return ((int)(this["TranTxnTypeIdx"]));
            }
            set {
                this["TranTxnTypeIdx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("42")]
        public decimal TranAmtPurch {
            get {
                return ((decimal)(this["TranAmtPurch"]));
            }
            set {
                this["TranAmtPurch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal TranAmtCash {
            get {
                return ((decimal)(this["TranAmtCash"]));
            }
            set {
                this["TranAmtCash"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TranAuthNo {
            get {
                return ((int)(this["TranAuthNo"]));
            }
            set {
                this["TranAuthNo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TranRRN {
            get {
                return ((string)(this["TranRRN"]));
            }
            set {
                this["TranRRN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TranPANSrcIdx {
            get {
                return ((int)(this["TranPANSrcIdx"]));
            }
            set {
                this["TranPANSrcIdx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TranAccountTypeIdx {
            get {
                return ((int)(this["TranAccountTypeIdx"]));
            }
            set {
                this["TranAccountTypeIdx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TranPAN {
            get {
                return ((string)(this["TranPAN"]));
            }
            set {
                this["TranPAN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TranExpiry {
            get {
                return ((string)(this["TranExpiry"]));
            }
            set {
                this["TranExpiry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TranCurrCodeIdx {
            get {
                return ((int)(this["TranCurrCodeIdx"]));
            }
            set {
                this["TranCurrCodeIdx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TranOriginalTxnTypeIdx {
            get {
                return ((int)(this["TranOriginalTxnTypeIdx"]));
            }
            set {
                this["TranOriginalTxnTypeIdx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TranTrainingMode {
            get {
                return ((bool)(this["TranTrainingMode"]));
            }
            set {
                this["TranTrainingMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TranEnableTip {
            get {
                return ((bool)(this["TranEnableTip"]));
            }
            set {
                this["TranEnableTip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TranPrintTimeout {
            get {
                return ((bool)(this["TranPrintTimeout"]));
            }
            set {
                this["TranPrintTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TranPrePrintTimeout {
            get {
                return ((bool)(this["TranPrePrintTimeout"]));
            }
            set {
                this["TranPrePrintTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TranAppendLastRFN {
            get {
                return ((bool)(this["TranAppendLastRFN"]));
            }
            set {
                this["TranAppendLastRFN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TranAppendSKU {
            get {
                return ((bool)(this["TranAppendSKU"]));
            }
            set {
                this["TranAppendSKU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TranAppendOPR {
            get {
                return ((bool)(this["TranAppendOPR"]));
            }
            set {
                this["TranAppendOPR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TranAppendAMT {
            get {
                return ((bool)(this["TranAppendAMT"]));
            }
            set {
                this["TranAppendAMT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TranAppendUID {
            get {
                return ((bool)(this["TranAppendUID"]));
            }
            set {
                this["TranAppendUID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TranAppendNME {
            get {
                return ((bool)(this["TranAppendNME"]));
            }
            set {
                this["TranAppendNME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TranAppendVER {
            get {
                return ((bool)(this["TranAppendVER"]));
            }
            set {
                this["TranAppendVER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TranAppendVND {
            get {
                return ((bool)(this["TranAppendVND"]));
            }
            set {
                this["TranAppendVND"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TranAppendPCM {
            get {
                return ((bool)(this["TranAppendPCM"]));
            }
            set {
                this["TranAppendPCM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TranPCMBarcode {
            get {
                return ((bool)(this["TranPCMBarcode"]));
            }
            set {
                this["TranPCMBarcode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TranSelectedTrack2 {
            get {
                return ((string)(this["TranSelectedTrack2"]));
            }
            set {
                this["TranSelectedTrack2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int QueryTypeIdx {
            get {
                return ((int)(this["QueryTypeIdx"]));
            }
            set {
                this["QueryTypeIdx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConfigTerminalId {
            get {
                return ((string)(this["ConfigTerminalId"]));
            }
            set {
                this["ConfigTerminalId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConfigMerchantId {
            get {
                return ((string)(this["ConfigMerchantId"]));
            }
            set {
                this["ConfigMerchantId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ConfigNII {
            get {
                return ((int)(this["ConfigNII"]));
            }
            set {
                this["ConfigNII"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ConfigAIIC {
            get {
                return ((int)(this["ConfigAIIC"]));
            }
            set {
                this["ConfigAIIC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45")]
        public int ConfigTimeout {
            get {
                return ((int)(this["ConfigTimeout"]));
            }
            set {
                this["ConfigTimeout"] = value;
            }
        }
    }
}
